# Kubernetes: Production-Grade Container Orchestration — lesson m08l01 — Package The Service As A Helm Chart
# https://learnsome.tech/courses/kubernetes-course/watch?lesson=m08l01
# © LearnSome.tech
replicaCount: 2
image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.29-alpine
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
