# Kubernetes: Production-Grade Container Orchestration — lesson m01l01 — From Docker To Desired State
# https://learnsome.tech/courses/kubernetes-course/watch?lesson=m01l01
# © LearnSome.tech
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
