# Kubernetes: Production-Grade Container Orchestration — lesson m04l02 — Volumes, PersistentVolumes And PersistentVolumeClaims
# https://learnsome.tech/courses/kubernetes-course/watch?lesson=m04l02
# © LearnSome.tech
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
