# Kubernetes: Production-Grade Container Orchestration — lesson m06l01 — Authentication, ServiceAccounts And Short Lived Tokens
# https://learnsome.tech/courses/kubernetes-course/watch?lesson=m06l01
# © LearnSome.tech
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  serviceAccountName: web
  automountServiceAccountToken: true
  containers:
    - name: web
      image: nginxinc/nginx-unprivileged:1.29-alpine
